version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/php"
  secrets-manager:
    APP_KEY: dev/AppKey:APP_KEY
phases:
  pre_build:
    commands:
      - IMAGE_TAG="$(git describe --tags)"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Running composer install in the service directory...
      - cd service
      - composer install --no-dev
      - cp .env.example .env
      - sed -i "s|APP_KEY=.*|APP_KEY=$APP_KEY|" .env 
      - cd ..
  build:
    commands:
      - echo Building the Docker image for ARM architecture...
      - docker buildx build --platform linux/amd64 -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"laravel-app","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $IMAGE_REPO_NAME $IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
