version: "3.8"
services:
  web:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:v1.7.3
    container_name: nginx-web
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/local.conf:/etc/nginx/conf.d/default.conf
      # - ./service:/var/www/html
      # - ./web/dist:/var/www/html/public
  php:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/base-php:8.2.13
    container_name: php-app
    platform: linux/amd64
    volumes:
      - ./service:/var/www/html
    working_dir: /var/www/html
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./service:/var/www/html
    working_dir: /var/www/html
    command: composer install
    depends_on:
      - php
