version: "3.8"
services:
  web:
    image: app-nginx
    platform: linux/amd64
    container_name: web
    ports:
      - "80:80"
  php:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/php:v1.2
    platform: linux/amd64
    container_name: app
    environment:
      APP_KEY: base64:DwKEvaOndVM7y64k8G1AZkjm/WkeKV3IyGsgf0tN9Uw=
