version: "3.8"
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./service:/var/www/html
    depends_on:
      - php
  php:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/php:v1.3
    platform: linux/amd64
    container_name: app
    # volumes:
    #   - ./service:/var/www/html
