version: "3.8"
services:
  web:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:v1.5.2
    container_name: nginx-web
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/local.default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: 720749898583.dkr.ecr.ap-northeast-1.amazonaws.com/php:v1.5.2
    container_name: php-app
    platform: linux/amd64
    env_file:
      - ./service/.env
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./service:/var/www/html
    working_dir: /var/www/html
    command: composer install
    depends_on:
      - php
