version: "3.8"
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./service:/var/www/html
    depends_on:
      - php
  php:
    image: ghcr.io/yoshitaka-motomura/php:8.2.12
    container_name: app
    volumes:
      - ./service:/var/www/html
