name: Laravel Lint Check
on:
  push:
    branches: [feature/*]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run lint check
        run: composer run lint
